---
# tasks file for bootstrap

- name: register apt_get
  raw: apt-get --version
  register: apt_get
  changed_when: no
  failed_when: no
  become: no
  check_mode: no

- name: register yum
  raw: yum --version
  register: yum
  changed_when: no
  failed_when: no
  become: no
  check_mode: no

- name: install software with apt-get
  raw: apt-get update ; apt-get -y install python sudo
  become: yes
  when:
    - apt_get.rc == 0
  register: apt_getresult
  changed_when:
    - "' 0 newly installed' not in apt_getresult.stdout"
  remote_user: "{{ bootstrap_user }}"
  until: apt_getresult is succeeded
  retries: 3

- name: install software with yum
  raw: yum -y install python2 sudo
  become: yes
  when:
    - yum.rc == 0
  register: yumresult
  changed_when:
    - "'Nothing' not in yumresult.stdout"
  remote_user: "{{ bootstrap_user }}"
  until: yumresult is succeeded
  retries: 3

- name: gather facts
  setup:
  become: no

- name: install software to support stable modules
  become: yes
  package:
    name: "{{ item }}"
  with_items:
    - "{{ bootstrap_packages['stable'][ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(bootstrap_packages['stable'][ansible_distribution]
      | default(bootstrap_packages['stable']['default'] )) }}"
  register: packagestableresult
  until: packagestableresult is succeeded
  retries: 3

- name: install software to support preview modules
  become: yes
  package:
    name: "{{ item }}"
  with_items:
    - "{{ bootstrap_packages['preview'][ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(bootstrap_packages['preview'][ansible_distribution]
      | default(bootstrap_packages['preview']['default'] )) }}"
  when:
    - bootstrap_preview
  register: packagepreviewresult
  until: packagepreviewresult is succeeded
  retries: 3

- name: gather facts after installation of packages
  setup:
  become: no
